name: Build and Test

on:
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  TEAMCITY_PASSWORD: ${{secrets.TEAMCITY_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Setup TeamCity Data Folder
      run: |
        cp target/applitools-eyes.zip tests/docker/plugins
        chmod -R 777 tests/docker
    
    - name: Run tests
      run: |
        cd tests
        mvn test
      env:
        APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
        TEAMCITY_PASSWORD: ${{ secrets.TEAMCITY_PASSWORD }}