name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Pull TeamCity Docker image
      run: docker pull jetbrains/teamcity-server

    - name: Run TeamCity Docker container
      run: docker run -d -p 8111:8111 --name teamcity_container jetbrains/teamcity-server

    - name: Copy plugin to Docker container
      run: |
        docker exec teamcity_container mkdir -p /data/teamcity_server/datadir/plugins/
        docker cp target/applitools-eyes.zip teamcity_container:/data/teamcity_server/datadir/plugins/
      
    - name: Run tests
      run: |
        cd tests
        mvn test
      env:
        APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}