name: Build and Test

on:
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Build Docker image
      run: | 
        cp -r target tests/docker
        cd tests
        docker build -t teamcity_container .
        docker run -d -p 8111:8111 --name teamcity_container teamcity_container
      
    - name: Run tests
      run: |
        cd tests
        mvn test
      env:
        APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}